### ISSUE TITLE
Custom Icons with Names >=KDBX 4.1 KeePass 2.48

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [Eveldee/KeePass-ExeIconPicker#5]
With [KeePass 2.48](https://keepass.info/news/n210507_2.48.html) a [new database format version](https://keepass.info/help/kb/kdbx_4.1.html#ci) was introduced, that supports icon names.

It would be nice to have support for this.
I could think of using the file name, the icon was fetched from, for the icons name. So that you can prevent duplicate redundancy icon storage in db for multiple entry or account of same program. Or if you start icon picking, to fallback to lookup for existing icons that match `Name` to the part if `LastModificationTime` is not too old.

**Comment by Eveldee** [comment]
I'm going to check how to add names for the icons, using the picked filename as the name.

I don't think I will implement a duplication check using icon names because two different programs can have the same name and different icons.
Besides, it's possible that two icons have the same name in the database since it's not unique, which will lead to issues.
I don't see any way to check for duplicates except using hash but it will be slow to check against all icons each time, maybe an extension only dedicated to find duplicates will be more suitable, I can try to make one if nobody has done it yet.

Edit: opened a new issue for the duplication feature #6
